steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/sign-certificate-function', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sign-certificate-function']

  # Set IAM policy for public access
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'beta'
      - 'run'
      - 'services'
      - 'add-iam-policy-binding'
      - 'sign-certificate-service'
      - '--region'
      - 'europe-west1'
      - '--member'
      - 'allUsers'
      - '--role'
      - 'roles/run.invoker'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'sign-certificate-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/sign-certificate-function'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--concurrency'
      - '80'
      - '--service-account'
      - 'firebase-adminsdk-fbsvc@adeverinte-app-b8cc1.iam.gserviceaccount.com'

images:
  - 'gcr.io/$PROJECT_ID/sign-certificate-function' 